version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-mqtt-broker
    hostname: mqtt-broker
    ports:
      - "${MQTT_PORT:-4883}:${MQTT_INTERNAL_PORT:-1883}"    # MQTT 標準端口
      - "${MQTT_TLS_PORT:-4884}:${MQTT_TLS_INTERNAL_PORT:-8883}"    # MQTT over TLS 加密端口
      - "${MQTT_WS_PORT:-9021}:${MQTT_WS_INTERNAL_PORT:-9001}"    # WebSocket 端口 (可選)
    volumes:
      # 配置文件 (只讀掛載)
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./acl:/mosquitto/config/acl:ro
      - ./passwd:/mosquitto/config/passwd:ro
      - ./certs:/mosquitto/certs:ro
      # 數據目錄 (讀寫掛載)
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - TZ=${TIMEZONE:-Asia/Taipei}                    # 時區設置
      - MQTT_BROKER_IP=${MQTT_BROKER_IP:-140.134.60.218}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -h localhost -t health/check -m ping -q || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET:-172.20.0.0/16}
          gateway: ${DOCKER_GATEWAY:-172.20.0.1}
